name: Push to Buf Schema Registry
on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - "proto/**"

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.15.1
      - uses: bufbuild/buf-push-action@v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
